export const MAP_EXPLORE_INIT_POSITION = 'map-init-position';
export const MAP_EXPLORE_INIT_POSITION_EMPTY_LIST = [];

export const MAP_EXPLORE_INIT_LATITUDE = 37.580103;
export const MAP_EXPLORE_INIT_LONGITUDE = 126.983113;

export const POPUP_FULL_SIZE_POSITION = 0;
export const POPUP_MIDDLE_SIZE_POSITION = 300;
export const POPUP_SMALL_SIZE_POSITION = 500;

export const MAP_CONTENT_POST_TYPE = 'POST_TYPE';
export const MAP_CONTENT_LOCATION_TYPE = 'LOCATION_TYPE';
