export const NOTIFICATION_CONTENT_TEXT_TYPE = 'TEXT';

export const NOTIFICATION_CONTENT_IMAGE_TYPE = 'IMAGE';

export const NOTIFICATION_CONTENT_NONE_TYPE = 'NONE';

export const NOTIFICATION_MSG_MAX_RETATION_DAY = 7;

//메시지
export const MESSAGE_NOTIFICATION_TYPE = 'MESSAGE_NOTIFICATION';

// 게시글
export const POST_LIKE_NOTIFICATION_TYPE = 'POST_LIKE_NOTIFICATION';
export const POST_CLIP_NOTIFICATION_TYPE = 'POST_CLIP_NOTIFICATION';

// 게시글 댓글
export const POST_COMMENT_NOTIFICATION_TYPE = 'POST_COMMENT_NOTIFICATION';
export const POST_COMMENT_LIKE_NOTIFICATION_TYPE =
  'POST_COMMENT_LIKE_NOTIFICATION';
export const POST_COMMENT_REPLY_NOTIFICATION_TYPE =
  'POST_COMMENT_REPLY_NOTIFICATION';

//팔로우
export const USER_FOLLOWER_NOTIFICATION_TYPE = 'USER_FOLLOWER_NOTIFICATION';
