export const MAX_POST_COMPOSE_SOURCE_DELAY_TIME = 5000;
export const POST_COMPOSEUPLOAD_MAX_NUM = 5;
export const POST_VIDEOCOMPOSEUPLOAD_MAX_NUM = 1;

export const POST_COMPOSE_IMG_RATIO = 4;

export const MAX_POST_VIDEO_DURATION = 180; //3분 : 60 *3

export const POST_COMPOSE_HEADER_TITLE_PHRASE = '새 게시물';
export const POST_VIDEO_COMPOSE_HEADER_TITLE_PHRASE = '영상';
export const POST_COMPOSE_BUTTON_PHRASE = '게시물 업로드';
