export const RECENTLY_WORD_LIST_NUM = 20;
export const SEARCH_RELATION_QUERY_DELAY_MIRCE_TIME = 600; //ms

export const SEARCH_WORD_LOCATION_TYPE = 'LOCATION_WORD_TYPE';
export const SEARCH_WORD_POST_TYPE = 'LOCATION_POST_TYPE';
