// 가입 종류
export const SINGUP_KAKAO_LOGIN_JOIN_TYPE = 'KAKAO';
export const SINGUP_NAVER_LOGIN_JOIN_TYPE = 'NAVER';
export const SINGUP_GOOGLE_LOGIN_JOIN_TYPE = 'GOOGLE';
export const SINGUP_APPLE_LOGIN_JOIN_TYPE = 'APPLE';
export const SINGUP_EMAIL_JOIN_TYPE = 'EMAIL';

export const SIGNUP_NICKNAME_INPUT_STEP_VALUE = 1;
export const SIGNUP_NICKNAME_INPUT_STEP_QUERY_PARAM_VALUE = 'nickaname';
export const SIGNUP_BIRTHDATE_INPUT_STEP_VALUE = 2;
export const SIGNUP_BIRTHDATE_INPUT_STEP_QUERY_PARAM_VALUE = 'birthdate';
export const SIGNUP_GENDER_INPUT_STEP_VALUE = 3;
export const SIGNUP_GENDER_INPUT_STEP_QUERY_PARAM_VALUE = 'gender';
export const SIGNUP_USERNAME_INPUT_STEP_VALUE = 4;
export const SIGNUP_USERNAME_INPUT_STEP_QUERY_PARAM_VALUE = 'username';
export const SIGNUP_FAVORITE_TAG_INPUT_STEP_VALUE = 5;
export const SIGNUP_FAVORITE_TAG_INPUT_STEP_QUERY_PARAM_VALUE = 'favorite_tags';
export const SIGNUP_TERM_OF_SERVICE_STEP_VALUE = 6;
export const SIGNUP_TERM_OF_SERVICE_QUERY_PARAM_VALUE = 'term_of_service';

// 유저 아이디 정보
export const SIGNUP_USERNAME_MIN_SIZE = 5;
export const SIGNUP_USERNAME_MAX_SIZE = 18;

export const SIGNUP_NICKNAME_MIN_SIZE = 2;
export const SIGNUP_NICKNAME_MAX_SIZE = 30;

export const SIGNUP_PASSWORD_MIN_SIZE = 8;
export const SIGNUP_PASSWORD_MAX_SIZE = 20;

export const SIGNUP_PASSWORD_SPECIAL_CHAR_CHECK_FILTER = `!@_`;

export const SIGNUP_FAVORITE_TAG_MAX_NUM = 5;

export const SIGNUP_MIN_AGE = 14;

export const SIGNUP_GENDER_FEMALE_CATEGORY = 'FEMALE';
export const SIGNUP_GENDER_FEMALE_TITLE = '여자';

export const SIGNUP_GENDER_MALE_CATEGORY = 'MALE';
export const SIGNUP_GENDER_MALE_TITLE = '남자';

export const SIGNUP_GENDER_OTHERS_CATEGORY = 'OTHERS';
export const SIGNUP_GENDER_OTHERS_TITLE = '선택 안함';

export const MAX_DELETED_USER_RETENTION_DAY = 14;
