export const UPLOAD_IMG_MAX_WIDTH = 1024;
export const UPLOAD_IMG_MAX_HEIGHT = 1024;

export const MAX_DELAY_SETTIMEOUT_TIME = 30;

export const MSG_MAX_DELAY_SETTIMEOUT_TIME = 50;

export const MEDIA_MOBILE_MAX_WIDTH_NUM = 1200;
export const MEDIA_MOBILE_MAX_WIDTH = `${MEDIA_MOBILE_MAX_WIDTH_NUM}px`;

export const MEDIA_MIDDLE_WIDTH_NUM = 1550;
export const MEDIA_MIDDLE_WIDTH = `${MEDIA_MIDDLE_WIDTH_NUM}px`;

export const MEDIA_MIDDLE_1300_WIDTH_NUM = 1300;
export const MEDIA_MIDDLE_1300_WIDTH = `${MEDIA_MIDDLE_1300_WIDTH_NUM}px`;

export const MEDIA_MIDDLE_1400_WIDTH_NUM = 1400;
export const MEDIA_MIDDLE_1400_WIDTH = `${MEDIA_MIDDLE_1400_WIDTH_NUM}px`;

export const SERVER_PATH = process.env.REACT_APP_SERVER_PATH;
export const SERVER_API_PATH = process.env.REACT_APP_SERVER_API_URL;
export const WEBSOCKET_URL = process.env.REACT_APP_WEBSOCKET_URL;

export const SERVICE_USAGE_TIME = 1000 * 60 * 4; // 4분;
