export const UserReportType = {
  USER_INAPPROPRIATE_CONTENT: 'INAPPROPRIATE_CONTENT',
  USER_SPAM_OR_PROMOTIONAL_CONTENT: 'SPAM_OR_PROMOTIONAL_CONTENT',
  USER_FALSE_INFORMATION_FRAUD: 'FALSE_INFORMATION_FRAUD',
  USER_PRIVACY_VIOLATION: 'PRIVACY_VIOLATION',
  USER_COPYRIGHT_INFRINGEMENT: 'COPYRIGHT_INFRINGEMENT',
  USER_HARASSMENT_OR_BULLYING: 'HARASSMENT_OR_BULLYING',
  USER_OTHER_REASON: 'OTHER',
} as const;
type UserReportType = (typeof UserReportType)[keyof typeof UserReportType];
