import {
  MESSAGE_CONVERSTAION_PATH,
  MESSAGE_INBOX_PATH,
  POST_COMPOSE_PATH,
  PROFILE_CLIP_LIST_PATH,
  PROFILE_SCRAP_LIST_PATH,
} from './PathConst';

export const UNAUTHORIZED_ERROR_STOMP_DELIVERY_MESSAGE = 'UNAUTHORIZED';
export const ACCESS_TOKEN_EXPIRED_ERROR_STOMP_DELIVERY_MESSAGE =
  'EXPIRED_ACCESS_TOKEN_EXCEPTION';

export const UNAUTHORIZED_ERROR_LINK_LIST = [
  MESSAGE_INBOX_PATH,
  MESSAGE_CONVERSTAION_PATH,
  PROFILE_CLIP_LIST_PATH,
  PROFILE_SCRAP_LIST_PATH,
  POST_COMPOSE_PATH,
];
